import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { HeaderWrapper } from '@/components/HeaderWrapper';
import { Footer } from '@/components/Footer';
import { CityProvider } from '@/context/CityContext';
import { StructuredData } from '@/components/StructuredData';

const inter = Inter({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin', 'latin-ext'],
  display: 'swap',
});

export const metadata: Metadata = {
  metadataBase: new URL('https://namazvakitleri.com'),
  title: {
    template: '%s | Namaz ve İftar Vakitleri',
    default: 'Namaz Vakitleri - Türkiye Geneli Namaz ve İftar Saatleri',
  },
  description: "Türkiye'deki tüm şehirler için güncel namaz vakitleri, iftar ve sahur saatleri. Diyanet onaylı vakit bilgileri ile canlı geri sayım. İstanbul, Ankara, İzmir ve 81 il için namaz saatleri.",
  keywords: [
    'namaz vakitleri',
    'iftar vakti',
    'sahur vakti',
    'ezan saati',
    'namaz saatleri',
    'diyanet namaz vakitleri',
    'istanbul namaz vakti',
    'ankara namaz vakti',
    'iftar saati',
    'sahur saati',
    'ramazan',
    'imsak vakti',
    'akşam ezanı',
    'öğle namazı',
    'ikindi namazı',
    'yatsı namazı',
  ],
  alternates: {
    canonical: 'https://namazvakitleri.com',
  },
  authors: [{ name: 'Namaz Vakitleri' }],
  creator: 'Namaz Vakitleri',
  publisher: 'Namaz Vakitleri',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'tr_TR',
    url: 'https://namazvakitleri.com',
    siteName: 'Namaz ve İftar Vakitleri',
    title: 'Namaz Vakitleri - Türkiye Geneli Namaz ve İftar Saatleri',
    description: "Türkiye'deki tüm şehirler için güncel namaz vakitleri, iftar ve sahur saatleri. Diyanet onaylı vakit bilgileri.",
    // images are auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Namaz Vakitleri - Türkiye Geneli Namaz ve İftar Saatleri',
    description: "Türkiye'deki tüm şehirler için güncel namaz vakitleri, iftar ve sahur saatleri.",
    // images are auto-generated by opengraph-image.tsx
    creator: '@namazvakitleri',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // verification: {
  //   google: 'GOOGLE_SEARCH_CONSOLE_VERIFICATION_CODE',
  //   yandex: 'YANDEX_WEBMASTER_VERIFICATION_CODE',
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <head>
        <StructuredData />
      </head>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <CityProvider>
          <HeaderWrapper />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </CityProvider>
      </body>
    </html>
  );
}
